### ISSUE TITLE
Declaration of Doctrine\Common\Reflection\StaticReflectionClass::getConstants() must be compatible with ReflectionClass::getConstants()

### ISSUE THREAD

**Issue by iVegas** [doctrine/reflection#46]
Recent tests using PHP 8.0.0-alpha1 shows method implementation incompatibility.
Drupal 9 PHP 8.0 compatibility issue https://www.drupal.org/project/drupal/issues/3109885#comment-13730977
Tests results https://www.drupal.org/pift-ci-job/1745466

**Comment by alexpott** [comment]
This should be addressed by https://github.com/doctrine/reflection/pull/43

**Comment by greg0ire** [comment]
@iVegas we are considering deprecating this class and the biggest part of this package, consider migrating to something else (`roave/better-reflection`?)

**Comment by Firehed** [comment]
`StaticReflectionMethod` is similarly affected:

`PHP Fatal error:  Declaration of Doctrine\Common\Reflection\StaticReflectionMethod::invoke($object, $parameter = null) must be compatible with ReflectionMethod::invoke(?object $object, mixed ...$args)`
